# Generated by Django 3.1.5 on 2021-02-12 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meme_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meme',
            old_name='meme_caption',
            new_name='caption',
        ),
        migrations.RenameField(
            model_name='meme',
            old_name='meme_author',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='meme',
            old_name='meme_url',
            new_name='url',
        ),
    ]
