# Generated by Django 3.1.5 on 2021-02-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_app', '0002_auto_20210212_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='url',
            field=models.URLField(max_length=300),
        ),
    ]
